version: "3.8"
services:
  public:
    container_name: public
    restart: on-failure
    build: ./public-service/
    ports:
      - "40000:40000"
    env_file:
      - ./public-service/.env.qa
    links:
      - subscription
  subscription:
    container_name: subscription
    restart: on-failure
    build: ./subscription-service/
    ports:
      - "40001:40001"
    env_file:
      - ./subscription-service/.env.qa
    links:
      - mongo
      - email
  email:
    container_name: email
    restart: on-failure
    build: ./email-service/
    ports:
      - "40002:40002"
    env_file:
      - ./email-service/.env
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    ports:
      - 3300:3000