version: "3.8"
services:
  public:
    container_name: public
    restart: on-failure
    build: ./public-service/
    ports:
      - "40000:40000"
    env_file:
      - ./public-service/.env.qa
    links:
      - subscription
    depends_on:
      - rabbitmq
  subscription:
    container_name: subscription
    restart: on-failure
    build: ./subscription-service/
    ports:
      - "40001:40003"
    env_file:
      - ./subscription-service/.env.qa
    links:
      - mongo
      - email
    depends_on:
      - rabbitmq
  email:
    container_name: email
    restart: on-failure
    build: ./email-service/
    ports:
      - "40002:40004"
    env_file:
      - ./email-service/.env.qa
    depends_on:
      - rabbitmq
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    ports:
      - 3300:3000
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=guest"
      - "RABBITMQ_DEFAULT_USER=guest"
    ports:
      - 15672:15672
      - 5672:5672
    hostname: my-rabbit